name: knowit_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - boost-cpp
  - cgal-cpp
  - cudatoolkit=11.8
  - pip:
      - -e .[torch,dev,extra-data]